### ISSUE TITLE
Cinema project issues

### ISSUE THREAD

**Issue by SanzharSuleimenov** [Sherovar/homework-everset#1]
Заметил пару недоработок:
1. buyPlace - При покупке билета, если он вводит место которое уже занято, то ты должен запросить повторный ввод места для покупки. Не нужно было возвращать пользователя в меню.
2. currentIncome - Ты каждый раз считаешь сумму заново. Это не эффективно.
3. countFreeSpaces - Ты каждый раз считаешь количество свободных мест. Тоже не эффективно.
4. Есть вольности по части ввода и вывода. На это можно не обращать внимания.

**Comment by Sherovar** [comment]
Updated
